### ISSUE TITLE
Insufficient RAM on createRandom()

### ISSUE THREAD

**Issue by han-so1omon** [LimeChain/eoslime#15]
I'm trying to create an account as such:
    `let dummy = await eoslime.Account.createRandom();`

My default account is defined as such:
```
let default_a = eoslime.Account.load(
  '...',
  '...')
eoslime.Provider.defaultAccount = default_a;
```
This throws an error that the created account has insufficient RAM. Is this a permissions error maybe? My default account is loaded with the active key.

Error message:
```

Error: the string "{\"code\":500,\"message\":\"Internal Service Error\",\"error\":{\"code\":3080001,\"name\":\"ram_usage_exceeded\",\"what\":\"Account using more than allotted RAM usage\",\"details\":[{\"message\":\"account la5414bbb2ce has insufficient ram; needs 2996 bytes has 0 bytes\",\"file\":\"resource_limits.cpp\",\"line_number\":213,\"method\":\"verify_account_ram_usage\"}]}}" was thrown, throw an Error :)
      at process._tickCallback (internal/process/next_tick.js:68:7)



```

**Comment by han-so1omon** [comment]
Also the error string from createEncrypted is insufficient, stating only `Account encryption: undefined`

**Comment by bakasura980** [comment]
Hi, @han-so1omon, i will have a free time to check it in the weekend. Apologise for that, I hope, this wont block you a lot :)

**Comment by han-so1omon** [comment]
Thank you. I have made some temporary accounts for now. This is on Kylin test network, which is not officially supported

**Comment by bakasura980** [comment]
Hi @han-so1omon, I fixed the error you reported in the development branch. Please check the updated Readme and try again your scenario. If it works, please close the issue, so I can upload the changes in master

**Comment by han-so1omon** [comment]
I will try this out in the next few days. I went with a different testing strategy, so I will finish those tests first.

**Comment by bakasura980** [comment]
@han-so1omon, did you manage to try it out? If so and if it works as you expected, could you close the issue in order for me to upload the changes to the master branch and update the npm package ?

**Comment by han-so1omon** [comment]
Trying this out. Was delayed with some dumb stuff

**Comment by han-so1omon** [comment]
This works :).
I am using version from command `npm install git://github.com/LimeChain/eoslime#development`
