### ISSUE TITLE
Eosjs error when executing action on kylin test chain (i.e. custom)

### ISSUE THREAD

**Issue by han-so1omon** [LimeChain/eoslime#17]
I am calling the create account action from my accounts contract as such. It produces an error about  an unknown key.
```

      await accounts_c.create(accounts_c.executor);

```

```
Error: {"code":500,"message":"Internal Service Error","error":{"code":0,"name":"exception","what":"unspecified","details":[{"message":"unknown key (eosio::chain::name): accounts","file":"http_plugin.cpp","line_number":653,"method":"handle_exception"}]}}
      at /home/uuu/project/node_modules/eosjs-api/lib/apigen.js:112:23
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by bakasura980** [comment]
Is accounts_c a contract ? And if so is `create` method a custom contract method ? Try with `await accounts_c.create(accounts_c.executor.name);`

**Comment by han-so1omon** [comment]
I will try this out this week. I have a some other testing to do first.

**Comment by han-so1omon** [comment]
Please re-open this. Getting the following error with the suggested method `await accounts_c.create(accounts_c.executor.name);`:
```
     Error: {"code":500,"message":"Internal Service Error","error":{"code":0,"name":"exception","what":"unspecified","details":[{"message":"unknown key (eosio::chain::name): accounts","file":"http_plugin.cpp","line_number":653,"method":"handle_exception"}]}}
      at /home/guy/projectnode_modules/eosjs-api/lib/apigen.js:112:23
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by han-so1omon** [comment]
Why would it say "unknown key" and then the name of the contract instead of the name of the account?

**Comment by han-so1omon** [comment]
When I change contract name to account name it works:
```
+    accounts_c = eoslime.Contract(ABI,CONTRACT_ACCOUNT_NAME,acct);
-    accounts_c = eoslime.Contract(ABI,CONTRACT_NAME,acct);
```
Is that the desired behavior?

**Comment by bakasura980** [comment]
I think you do the following [PSEUDO CODE]
```
// Contract
contract testcontract {}

// Javascript
const contractAccount = eoslime.load('myContractAccount', 'somePrivateKey')
```

In this case myContractAccount != testcontract. When you want you use
```
eoslime.Contract(ABI,CONTRACT_ACCOUNT_NAME,acct);
```
You should provide actually the account's name on which the contract is deployed. Please correct me if I wrong. From your issue I understood the above case.
I can change the documentation if there is a misunderstanding, how do you feel ?

**Comment by bakasura980** [comment]
Does your change above actually resolve your first issue in the thread or to look in depth and write some tests in order to reproduce your issue ?

**Comment by bakasura980** [comment]
Will close it due to no response
