### ISSUE TITLE
Provide functionality required to test sending an actions from one contract to another contract

### ISSUE THREAD

**Issue by vladichhh** [LimeChain/eoslime#20]
According to the official EOS developer documentation, in order to send inline actions from a contract, we have to add the "eosio.code" permission to the contract's account's active permission. Using the terminal and cleos the command is as follows:
```
cleos set account permission ${account_name} active --add-code
```
In addition I have noted that prior to add "eosio.code" permission, we have to import private key of the account to the default wallet.

**Comment by bakasura980** [comment]
Hi @vladichhh, your feature request is done. You can check the last version of eoslime and try it.

**Comment by vladichhh** [comment]
Thanks, @bakasura980. I have just tested and is working as expected.
