### ISSUE TITLE
Allow adding multiple permissions to an account

### ISSUE THREAD

**Issue by vladichhh** [LimeChain/eoslime#22]
Up to now we could add only the eosio.code permission to the contract's account's active permission (during contract deployment). But there are special cases, when we need to allow adding more permissions to the accounts.

Example: market contract, deployed along with token contract. Initially we will need eosio.code permission to be added to market account, in order to allow market contract to make external calls to the token contract. To complete issuing/transferring tokens, market contract has to authorise token account to act on its behalf.

```
{
  "account_name": "market",
  ...
  "permissions": [{
      "perm_name": "active",
      "parent": "owner",
      "required_auth": {
        "threshold": 1,
        "keys": [{
            "key": "market public key",
            "weight": 1
          }
        ],
        "accounts": [{
            "permission": {
              "actor": "market",
              "permission": "eosio.code"
            },
            "weight": 1
          },{
            "permission": {
              "actor": "token",
              "permission": "eosio.code"
            },
            "weight": 1
          }
        ],
        "waits": []
      }
    }
  ]
  ...
}
```
Using cleos:
```
cleos set account permission market active market --add-code
cleos set account permission market active token --add-code
```
Another use case is configuring buyer account, trying to buy something from the market and authorising the market contract to transfer buyers tokens to a specified recipient account:
```
"account_name": "buyer",
  "permissions": [{
      "perm_name": "active",
      "parent": "owner",
      "required_auth": {
        "threshold": 1,
        "keys": [{
            "key": "buyer public key",
            "weight": 1
          }
        ],
        "accounts": [{
            "permission": {
              "actor": "market",
              "permission": "eosio.code"
            },
            "weight": 1
          }
        ],
        "waits": []
      }
    }
```
Using cleos:
```
cleos set account permission buyer active market --add-code
```

**Comment by bakasura980** [comment]
Hey @vladichhh , could you check the new feature - allow another account to act on behalf, which is imported in v0.0.15. On `addPermission` method you have an optional argument - actor. I think this cover your suggestion.

**Comment by vladichhh** [comment]
Thanks, @bakasura980. I have just tested the last version 0.0.15. It is working as expected and I am going to close the issue.
