### ISSUE TITLE
Are you considering upgrading eosjs to version 20.0.0 as soon as possible?

### ISSUE THREAD

**Issue by cppfuns** [LimeChain/eoslime#24]

**Comment by bakasura980** [comment]
Hey @cppfuns, do you have something in mind if we upgrade to v20.0.0 ? We don't consider upgrading, but we have an idea to implement our functionality and remove eosjs. Unfortunately this is a free time project and we don't have so much time to work on it :(

**Comment by cppfuns** [comment]
Personally, there is no need to "make wheels". After all, eosjs is very functional and keeps up with the eos standard.

**Comment by bakasura980** [comment]
Thank you @cppfuns. We will have upgrading in mind for later improvements, but at the moment we have so much aims as a cli, separating the eoslime as a pluggable module in every js project(front-end/back-end) like ethers.js is and a test/cli module and etc.
