### ISSUE TITLE
transaction success, empalce data OK, but cannot read table rows by cleos get table contractName scope tableName

### ISSUE THREAD

**Issue by gao623** [LimeChain/eoslime#36]
Hi, using eoslime 1.0.1, my contract has an action "add", which is save data into table "datas", the scope is also contractName, 
 ```
 var Eoslime = require("eoslime");
  var eoslime = Eoslime .init(eosConfig);
...
  contractInstance = await eoslime.Contract.fromFile(abiPath, contractName, contractExecutorAccount);
  // success, if repaly this transaction, add action will throw "reduplicative record"
  await contractInstance.add(....);
  // result []
  var result = await eoslime.Provider.select("datas").from(contractInstance .name).scope(contractInstance .name).find();
  // result.rows []
  var result = eoslime.Provider.eos.getTableRows({json:true, code:contractInstance.name, scope:contractInstance.name, table:"datas"});
```
It is same with `cleos get table contractName contractName datas`  (0 rows)
I want to know, emplace table success in contract, but read no data from contract tables, what should I do?
ps: eosio.cdt 1.7 rc1

**Comment by bakasura980** [comment]
This seems to be something in your contract definition. Could you provide your contract code

**Comment by bakasura980** [comment]
Due to no response, I am going to close it
