### ISSUE TITLE
Provided keys, permissions, and delays do not satisfy declared authorizations

### ISSUE THREAD

**Issue by jochenonline** [LimeChain/eoslime#39]
When Trying to run my test with

    eoslime test

and calling

    eoslime.Contract.deploy(...., ....)

I get

Error: the string "{\"code\":500,\"message\":\"Internal Service Error\",\"error\":{\"code\":3090003,\"name\":\"unsatisfied_authorization\",\"what\":\"Provided keys, permissions, and delays do not satisfy declared authorizations\",\"details\":[{\"message\":\"transaction declares authority '{\\\"actor\\\":\\\"eosio\\\",\\\"permission\\\":\\\"active\\\"}', but does not have signatures for it under a provided delay of 0 ms, provided permissions [], provided keys [\\\"EOS7CZHcDrT6E4sWfSzjUQAM4NGyVkfH6La1QXqQPT1q2zc2NkEYB\\\"], and a delay max limit of 3888000000 ms\",\"file\":\"authorization_manager.cpp\",\"line_number\":532,\"method\":\"check_authorization\"}]}}" was thrown, throw an Error :)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

I have set 

    eoslime.Provider.defaultAccount.privateKey = "...";
    eoslime.Provider.defaultAccount.publicKey = "...";

But anyway this happens. What am I doing wrong?

**Comment by bakasura980** [comment]
Hey @jochenonline , thank you for your issue. What is the name of the account you are trying to deploy with? If it is not 'eosio', please also change the `defaultAccount.name` to yours

**Comment by jochenonline** [comment]
The account I try to deploy with is 'eosio'!

**Comment by jochenonline** [comment]
Deploying the contract via [this script](https://cmichel.io/setcode-and-setabi-with-eos-js/) and eosjs works perfectly. So it is no matter of misconfiguration or wrong keys.

**Comment by bakasura980** [comment]
Could you please try the following -> 
```
const contractAccount = await eoslime.Account.createRandom();
const contract = await eoslime.Contract.deployOnAccount(WASM, ABI, contractAccount);
```

Please return what is the result of the above. Also, please provide a code snippet, because at the moment your error is coming from the chain, not from the eoslime. At the moment I can have only suggestions, not solutions

**Comment by bakasura980** [comment]
Is `EOS7CZHcDrT6E4sWfSzjUQAM4NGyVkfH6La1QXqQPT1q2zc2NkEYB` the public key of the 'eosio' account, also you could try the following
```
const eosio = await eoslime.Account.load('eosio', 'private key');
eoslime.Provider.defaultAccount = eosio;
```

**Comment by jochenonline** [comment]
@bakasura980 : No, I have my own keypair. And yes, I have tried the version with Account.load already. Same result...

**Comment by bakasura980** [comment]
Alright, try to init eoslime with your network as a custom one

**Comment by bakasura980** [comment]
@jochenonline Did you find out the problem ?

**Comment by jochenonline** [comment]
It works now. Thank you for your hints. The final code to get eoslime initilaized correctly is as follows:

    const eoslime = require('eoslime').init({ url: 'http://127.0.0.1:8888', chainId: '<myChainId>' });
    let eosioAccount = await eoslime.Account.load("eosio", "<privateKeyOfEosio>", 'active');
    eoslime.Account.defaultAccount = eosioAccount;
