### ISSUE TITLE
feature/add_wasm_and_abi_download

### ISSUE THREAD

**Issue by Avm07** [LimeChain/eoslime#53]
As well know wasm and abi can be getted from [nodeos api](https://developers.eos.io/manuals/eos/latest/nodeos/plugins/chain_api_plugin/api-reference/index#operation/get_raw_code_and_abi)

Framework should be able to get it from nodeos, save to file and use it for tester class.
Because contract is deployed from ci/cd and tester want to get it and use it for deploy for his needs.

For example: create new account, deploy contract, run some cases with out reseting container.

**Comment by bakasura980** [comment]
Implemented in development branch with  commit - https://github.com/LimeChain/eoslime/commit/950ab467d7b593f538802c4d634664ba7f473293

**Comment by bakasura980** [comment]
Here is how you could use it in your code
```javascript
const eoslime = eoslime.init();
const deployedContract = 'your_contract_name'; 
const contractA_ABI = await eoslime.Provider.getABI(deployedContract);
const contractA_WASM = await eoslime.Provider.getRawWASM(deployedContract);

const contractB = await eoslime.Contract.deployRaw(contractA_WASM, contractA_ABI);
```

You have 2 new deployment methods - deployRaw() ; deployRawOnAccount()

**Comment by Avm07** [comment]
Seems good.
