### ISSUE TITLE
TypeError: Contract.actionname is not a function

### ISSUE THREAD

**Issue by varshadqz** [LimeChain/eoslime#59]
This is my test file:

```
const assert = require('assert');

const TOKEN_WASM_PATH = './contracts/group/group.wasm';
const TOKEN_ABI_PATH = './contracts/group/group.abi';

describe("EOSIO Group", function (eoslime) {

    this.timeout(15000);

    let groupContract;
        let groupTable;
        let adminAccount;

    before(async () => {
            adminAccount = await eoslime.Account.load('groupaccount','myPK','active');
    });

    before(async () => {
        groupContract = eoslime.Contract.at(TOKEN_ABI_PATH, 'group', adminAccount);
        groupTable = groupContract.groups;
    });

    it("Should create a new group", async () => {
             await groupContract.upsertgroup("group2", "Assistant", "normal user include all users", "Common", 1,{ from: adminAccount.name });
    });
```

It is giving error on `eoslime test`:
 ```
1) EOSIO Group
      UnhandledPromiseRejectionWarning: Error: Provided String is not an instance of BaseAccount
       Should create a new group:
     TypeError: groupContract.upsertgroup is not a function
      at Context.it (tests/example-tests.js:37:27)
```

Contract name is "group", it is deployed on the account which is loaded here in before(). So, I don't need to deploy it here again. Only access contract and call its actions. Please help.

**Comment by bakasura980** [comment]
Hey @varshadqz, ```Contract.at``` accepts only 2 parameters -> contract name and contract executor. You are providing 3 and TokenAbi is actually a string, not an account. That the reason for the error.

**Comment by varshadqz** [comment]
Hi @bakasura980 please clear me some things. Contract name means actually the name of the contract which I am providing in the smart contract (name of .cpp file) or account name on which the contract is deployed?

**Comment by varshadqz** [comment]
If I give 2 parameters:
I am using only one account for everything. 
```
const adminAccount ;
 adminAccount = await eoslime.Account.load('account name on which contract is deployed','PK');
Contract = eoslime.Contract.at('account name on which contract is deployed',adminAccount);
```

Still error,

> TypeError: Contract.send is not a function

Note: In https://docs.eoslime.limechain.tech/developer-documentation/contract documentation, it has 3 parameters including abi.

**Comment by bakasura980** [comment]
You are using `.at` method -> https://docs.eoslime.limechain.tech/developer-documentation/contract/instantiation#at-contractname-executor. Provide ABI in case of cold instantiation -> no request to the blockchain

**Comment by bakasura980** [comment]
```Contract = await eoslime.Contract.at('account name on which contract is deployed',adminAccount);```

**Comment by varshadqz** [comment]
Okay, thank you for clearing doubt. But even if eoslime is installed.
for the line:
`const eoslime = require('eoslime').init();`

it gives error:

> (node:9209) UnhandledPromiseRejectionWarning: Error: Cannot find module 'eoslime'

**Comment by bakasura980** [comment]
How did you install it ? -> `npm install eoslime` installs it locally as a package - to use as CLI
```package.json
"scripts" : {
   "test": "eoslime test"
}
```

I think in your case you have installed it globally, right ?

**Comment by varshadqz** [comment]
Yes, when I tried `npm install eoslime` It gives:

```
npm WARN eoslime-project@1.0.0 No repository field.
npm ERR! Linux 4.4.0-18362-Microsoft
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "eoslime"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! path /home/varshakhandre14/eoslime/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/home/varshakhandre14/eoslime/node_modules'
npm ERR!  { Error: EACCES: permission denied, access '/home/varshakhandre14/eoslime/node_modules'
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/home/varshakhandre14/eoslime/node_modules' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.
```

So, I use `sudo npm install -g eoslime`.  Sorry, not so good with node.

**Comment by bakasura980** [comment]
No worries, It is strange, try to do `sudo npm install eoslime`

**Comment by bakasura980** [comment]
Is your project located in your root directory

**Comment by varshadqz** [comment]
yes, it is in the root directory. I tried to fix the installing issue and set :
```
sudo chown -R varshakhandre14/usr/local/lib/node_modules/
sudo chown -R varshakhandre14/usr/local/bin/
sudo chown -R varshakhandre14/usr/local/share/
```
Now `sudo npm install eoslime` gives:

```
npm ERR! tar pack Error reading /home/varshakhandre14/eoslime
npm ERR! addLocalDirectory Could not pack /home/varshakhandre14/eoslime to /home/varshakhandre14/.npm/eoslime-project/1.0.0/package.tgz
npm ERR! addLocal Could not install /home/varshakhandre14/eoslime
npm ERR! Linux 4.4.0-18362-Microsoft
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "eoslime"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! path /home/varshakhandre14/package/data/blocks/blocks.log

npm ERR! Didn't get expected byte count
npm ERR! expect: 4570302
npm ERR! actual: 4571070
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

**Comment by bakasura980** [comment]
I think root directory brokes the installation. Could you move your project somewhere else and try to install it ?

**Comment by varshadqz** [comment]
OK. let me know, I should run this `npm install -g eoslime` in root or in eoslime directory?

**Comment by bakasura980** [comment]
Nope, move your entire project in a folder different than the root one, after that do `npm install eoslime` in the folder of your project

**Comment by varshadqz** [comment]
Hey @bakasura980 , thanx a lot for your time and support. It solves the problem.
