### ISSUE TITLE
eosio v2.0.7 support

### ISSUE THREAD

**Issue by prcolaco** [LimeChain/eoslime#67]
when using eosio v2.0.7 eoslime doesn't work, not even starting the node:
```bash
$ eoslime nodeos start
===== Starting nodeos ... =====
===== Nodeos has not been started =====
{"code":500,"message":"Internal Service Error","error":{"code":3090003,"name":"unsatisfied_authorization","what":"Provided keys, permissions, and delays do not satisfy declared authorizations","details":[{"message":"transaction declares authority '{\"actor\":\"eosio\",\"permission\":\"active\"}', but does not have signatures for it under a provided delay of 0 ms, provided permissions [], provided keys [\"EOS8G55MNznVpDp2JMYsvDaW5WVzVGP21m9vCkb45KemcUf85Qjfp\"], and a delay max limit of 3888000000 ms","file":"authorization_manager.cpp","line_number":532,"method":"check_authorization"}]}}
```

same error when running tests:
```bash
$ eoslime nodeos start
===== Nodeos is already running =====
$ eoslime test

  Test xxx contract
    1) "before all" hook

  0 passing (1s)
  1 failing

  1) Test xxx contract
       "before all" hook:
     Error: the string "{\"code\":500,\"message\":\"Internal Service Error\",\"error\":{\"code\":3090003,\"name\":\"unsatisfied_authorization\",\"what\":\"Provided keys, permissions, and delays do not satisfy declared authorizations\",\"details\":[{\"message\":\"transaction declares authority '{\\\"actor\\\":\\\"eosio\\\",\\\"permission\\\":\\\"active\\\"}', but does not have signatures for it under a provided delay of 0 ms, provided permissions [], provided keys [\\\"EOS61mwtp14vU8HhJiXw9T6WAXaaNTXJjQjQ6fMUcy3e67oTTwzYj\\\"], and a delay max limit of 3888000000 ms\",\"file\":\"authorization_manager.cpp\",\"line_number\":532,\"method\":\"check_authorization\"}]}}" was thrown, throw an Error :)
      at process._tickCallback (internal/process/next_tick.js:68:7)



(node:20505) UnhandledPromiseRejectionWarning: 1
(node:20505) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:20505) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

going back to eosio v2.0.6 eliminates this problem.

**Comment by bakasura980** [comment]
Hey @prcolaco , could you provide me your script for starting a v2.0.7 node ?

**Comment by bakasura980** [comment]
What do you think about this: To be implemented a `--v-node` CLI option so one can start different versions of nodeos ?

**Comment by prcolaco** [comment]
> Hey @prcolaco , could you provide me your script for starting a v2.0.7 node ?

Don't really need anything special, just start a clean node, as one would expect, and as `eoslime nodeos start` does with eosio v2.0.6 but fails with eosio v2.0.7 with the errors I mentioned...
I am using MacOS 10.14.6 and clean block.one packages binaries installed with brew package manager, no special builds, or anything...

**Comment by prcolaco** [comment]
> What do you think about this: To be implemented a `--v-node` CLI option so one can start different versions of nodeos ?

Great idea! On development I usually use a vanilla install, but when I need a specific version I have my own builds with a `eosio/vX.Y.Z/*` structure for binaries and a script to map to the correct version with symlinks... but that is kind of a pain, so if eoslime could help on that would be very handy! ;)

**Comment by enginterzi** [comment]
I think the label is miss leading.
this should be labeled as a bug instead of an enhancement. 
I did not pay attention to this report because of the label until looking at the details. It cost me a couple of hours :)

**Comment by bakasura980** [comment]
@enginterzi - It not a bug, as all nodeos versions are working except 2.0.7 The version itself is incompatible

**Comment by NatPDeveloper** [comment]
same error for me on 2.0.8

**Comment by NatPDeveloper** [comment]
Any plans to fix this in the near term, or ideas to patch for the short term?  Would be nice to use 2.1, assuming it's the same issue.

**Comment by bakasura980** [comment]
@NatPDeveloper Yes, I have started implementing the fix
