### ISSUE TITLE
invalid_ref_block_exception

### ISSUE THREAD

**Issue by varshadqz** [LimeChain/eoslime#76]
I am trying to test a smart contract via eoslime. Using `nodeos`, but the node is not localhost(default). So, I installed and trying to deploy the smart contract using:
`eoslime deploy --network.url="http://***.***.***.***:8888" --network.chainId="cf057bbfb72640471fd910bcb67639c22df9f92470936cddc1ade0e2f2e7dc4f"`
It gives the following error:
```
===== Deployment has started... =====
===== Unsuccessful deployment of deploy.js =====
{"code":500,"message":"Internal Service Error","error":{"code":3040007,"name":"invalid_ref_block_exception","what":"Invalid Reference Block","details":[{"message":"Transaction's reference block did not match. Is this transaction from a different fork?","file":"controller.cpp","line_number":3158,"method":"validate_tapos"},{"message":"","file":"controller.cpp","line_number":3159,"method":"validate_tapos"}]}}
```
If I check `nodeos `details it gives correct details using:
`curl http://***.***.***.***:8888/v1/chain/get_info`

`Nodeos `is running, the transactions are done using cleos but not from eoslime test file. Please help.

**Comment by bakasura980** [comment]
Hi @varshadqz, is it a private network? What is the version of the nodeos? Does the deployment work on localhost? Have you tried to deploy on jungle?

**Comment by varshadqz** [comment]
It is private nodeos. I just added `--http-server-address=***.***.***.***:8888 ` to the nodeos command. Version of nodeos is : `"server_full_version_string":"v2.0.6-c6a7ec0dd816f98a6840f59dca9fed04efd9f7a5"` . Localhost is not working, it considers `127.0.0.1:8888` and `***.***.***.***:8888` different. No, I haven't tried on any other network.

**Comment by varshadqz** [comment]
Even if I am trying to push transaction using **cleos**, it giving same error as: 
```
Error 3040007: Invalid Reference Block
Ensure that the reference block exist in the blockchain!
Error Details:
Transaction's reference block did not match. Is this transaction from a different fork?
```
Not getting this error. I did hard-replay on **nodeos** and try again but the same problem.

**Comment by varshadqz** [comment]
Sorry, the issue was closed by mistake.

**Comment by bakasura980** [comment]
@varshadqz If you use cleos, do you have the same error? I got confused 😄

**Comment by varshadqz** [comment]
Hi @bakasura980 
yes, the later same issue was generated for cleos. I delete all blocks and started the **nodeos** again as a fresh. So problem solved by this.

**Comment by bakasura980** [comment]
Hi @varshadqz , thanks for your update. Could you please close the issue

**Comment by varshadqz** [comment]
Thank you!
