### ISSUE TITLE
Record not exist error even if record exist.

### ISSUE THREAD

**Issue by varshadqz** [LimeChain/eoslime#79]
I installed eoslime version 2.0.0, below is my test code:

```
const assert = require('assert');
const TOKEN_WASM_PATH = './contracts/commoncontract/commoncontract.wasm';
const TOKEN_ABI_PATH = './contracts/commoncontract/commoncontract.abi';
const CONTRACT_NAME = 'dispat';
const eoslime = require('eoslime').init('local', { url: 'http://127.0.0.1:8888', chainId: 'cf057bbfb72640471fd910bcb67639c22df9f92470936cddc1ade0e2f2e7dc4f' });

describe("EOSIO Unit testing", function (eoslime) {
        this.timeout(15000);

            let contract;
            let userTable; let groupTable;
            let adminAccount;

            before(async () => {

                                adminAccount = await eoslime.Account.load('dispat','myPK');
                        });

            before(async () => {
                                contract = await eoslime.Contract.at(CONTRACT_NAME,adminAccount);
                                userTable = contract.tables.usersindex;
                                groupTable = contract.tables.groupsindex;
                        });


                it("Should add group", async () => {
                        let user = await groupTable.limit(10).find();
                        console.log(user[0]);
                      
                        await contract.actions.upsertgroup("groupneww","grp11","admin","grp1cs","Admins group",1,"grp1#jdfhfdg78899","Varsha","Varsha");
                                        
                });
                it("Should remove User", async () => {
                        await contract.actions.eraseuser("eric");
                });
                it("Should remove Group", async () => {
                        await contract.actions.erasegroup("group1");
                });
});
```
When I try to test this file using ` eoslime test`, Even if I have record in the table it gives an error of no record exist from the smart contract. While If I display the table data it is displaying correct data but when  I try to delete that record it gives the wrong message. Calling actions is not successful in my case. Second thing is, I am passing bool value as integer value while inserting record for this `await contract.actions.upsertgroup("groupneww","grp11","admin","grp1cs","Admins group", 1,"grp1#jdfhfdg78899","Varsha","Varsha");` Its giving error of `Error: Number format uint8 n upsertgroup.isActive action.data transaction.actions`. What is this uint8 error?

**Comment by bakasura980** [comment]
`await contract.actions.upsertgroup("groupneww","grp11","admin","grp1cs","Admins group",1,"grp1#jdfhfdg78899","Varsha","Varsha");` has to be `await contract.actions.upsertgroup(["groupneww","grp11","admin","grp1cs","Admins group",1,"grp1#jdfhfdg78899","Varsha","Varsha"]);`

**Comment by bakasura980** [comment]
@varshadqz any updates on this ?

**Comment by varshadqz** [comment]
I switched to the old eoslime version where it works fine everything.

**Comment by bakasura980** [comment]
@varshadqz Is it okay to close the issue or we can have further discussion? If so, could you write in Telegram to have easier communication please

**Comment by varshadqz** [comment]
It's okay to close the issue. In future, if I got the same problem with the new version, can I reopen it?

**Comment by bakasura980** [comment]
@varshadqz , Of course. Just write in Telegram also to have our discussion there

**Comment by varshadqz** [comment]
Okay, Thank you!  I am closing the issue.
