### ISSUE TITLE
eoslime  deployment is failling

### ISSUE THREAD

**Issue by enginterzi** [LimeChain/eoslime#81]
I was testing the shape ready application. I could not be able to make it worked.

- I unluck the wallet on my local, it did not work,
- I killed a whole` pkill nodeos keosd~ and rm -rf ~/Library/Application\ Support/eosio/nodeos/data`
- I restart it, but the same problem

- BYW, I'm starting the nodeos as following 
`nodeos -e -p eosio --plugin eosio::producer_plugin --plugin eosio::producer_api_plugin --plugin eosio::chain_api_plugin --plugin eosio::http_plugin --plugin eosio::state_history_plugin --plugin eosio::history_api_plugin --max-transaction-time=10000 --access-control-allow-origin='*' --contracts-console --http-validate-host=false --trace-history --chain-state-history --verbose-http-errors --filter-on='*' --disable-replay-opts >> nodeos.log 2>&1 &`

- I also tried `eoslime deploy  --deployer EOS7Nn2F6UPiUqVf7CSQBneELWsEQiwHVSWW6isGcuBUBy9gHVaFH@active`

I'm sure I'm missing something, but I could not figure out what it is? 
Any idea?

===== Unsuccessful deployment of deploy.js =====
{"code":500,"message":"Internal Service Error","error":{"code":3090003,"name":"unsatisfied_authorization","what":"Provided keys, permissions, and delays do not satisfy declared authorizations","details":[{"message":"transaction declares authority '{\"actor\":\"eosio\",\"permission\":\"active\"}', but does not have signatures for it under a provided delay of 0 ms, provided permissions [], provided keys [\"EOS63rhpSP34M4ks9Qk69k8zyRtLX1ghrsyTuBx2weeHXKZKmVbb8\"], and a delay max limit of 3888000000 ms","file":"authorization_manager.cpp","line_number":532,"method":"check_authorization"}]}}

**Comment by enginterzi** [comment]
I resolved the issue to use EOS Studio instead of using local EOSIO.  
I exposed the EOSIO V.2.0.6 container. It worked. 
It's still an issue for the EOSIO V.2.0.7.

**Comment by bakasura980** [comment]
@enginterzi So you have managed to make it work and the problem is v2.0.7 actually, right ? If so we have already such an issue defined. Could you resolve that one ?

**Comment by enginterzi** [comment]
There is already a defined ticket regarding the issue.
